# Generated by Django 2.0.2 on 2020-03-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200316_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
